discord:
  token: ""
  channel: ""
tags:
  titles:
    ababa: "[ababa]"
  prefixes:
    ababa: "[ababa]"
    ububu: "[ububu]"
  suffixes:
    ububu: "[ububu]"
    ebebe:
      default: "[ebebe]"
      variants:
        '1': "[&1ebebe&r]"
        '2': "[&2ebebe&r]"
        '3': "[&3ebebe&r]"
commandspy-blacklist:
  - "list"
player-tracker:
  price: 1000
  # 0 = default eye behavior, 1 = always drop, 2 = never drop
  drop-type: 0